# Generated by Django 3.2.9 on 2021-11-28 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=120)),
                ('last_name', models.CharField(default='', max_length=120)),
                ('username', models.CharField(default='', max_length=120)),
                ('email', models.EmailField(default='', max_length=120)),
                ('password', models.CharField(default='', max_length=120)),
                ('role_id', models.CharField(default='', max_length=10)),
            ],
        ),
    ]
