# Generated by Django 3.2.9 on 2021-11-28 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20211128_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role_id',
            field=models.CharField(default='0', max_length=10, null=True),
        ),
    ]
