# Generated by Django 3.2.9 on 2021-11-28 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0003_auto_20211128_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
