# Generated by Django 3.2.9 on 2021-11-28 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.CharField(default='0', max_length=10, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='', max_length=120, unique=True)),
                ('desc', models.CharField(default='', max_length=120)),
            ],
        ),
    ]
