# Generated by Django 3.2.9 on 2021-11-28 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permission', '0002_alter_permission_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
